language: python

python:
  - "2.7"

install:
  - sudo apt-get update
  - sudo apt-get -y install cmake git hdf5-tools python2.7 python-pip unzip wget zlib1g-dev

  - pip install --upgrade pip
  - pip install cython numpy scipy

notifications:
  email:
    on_success: change
    on_failure: change


script:
  - sh ./install.sh
  - export PATH=$PATH:/home/travis/build/aldro61/kover/bin/
  - kover --version
  
  # Make sure that the k-mer tools exist and are in the correct directory
  - ls /home/travis/build/aldro61/kover/core/kover/dataset/tools/kmer_tools/dsk
  - ls /home/travis/build/aldro61/kover/core/kover/dataset/tools/kmer_tools/dsk2kover
  - ls /home/travis/build/aldro61/kover/core/kover/dataset/tools/kmer_tools/multidsk

  # Tutorial 1
  - mkdir tutorial_1
  - cd tutorial_1
  - wget https://github.com/aldro61/kover-tutorial-data/releases/download/1.0.0/kover-example-data.zip
  - unzip kover-example-data.zip
  - cd kover-example
  - kover dataset create from-tsv --genomic-data KmerMatrix.tsv --phenotype-description "Rifampicin resistance" --phenotype-metadata metadata.tsv --output example.kover --progress
  - kover dataset info --dataset example.kover --genome-count --kmer-count
  - kover dataset split --dataset example.kover --id example_split --train-size 0.666 --folds 5 --random-seed 72 --progress
  - kover learn scm --dataset example.kover --split example_split --model-type conjunction disjunction --p 0.1 1.0 10.0 --max-rules 5 --hp-choice cv --n-cpu 1 --progress
